#!/bin/bash

sudo apt-get remove docker docker-engine docker.io

curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

sudo apt-get update

apt-cache madison docker-ce

sudo apt-get install docker-ce
