#!/bin/bash

apt-get remove docker docker-engine docker.io

curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/debian \
   $(lsb_release -cs) \
   stable"

apt-get update

apt-cache madison docker-ce

apt-get install docker-ce=17.06.0~ce-0~debian-jessie
